"""Search term hints for royalty-free asset sourcing."""

from __future__ import annotations

# asset_id -> (primary query, prefer_short_one_shot)
# prefer_short: True for SFX/one-shots, False for ambience/music loops
ASSET_SEARCH_HINTS: dict[str, tuple[str, bool]] = {
    "AST-001": ("quiet indoor room atmosphere children", False),
    "AST-002": ("barbecue sizzle outdoor cooking", False),
    "AST-003": ("wooden cabin interior quiet room tone", False),
    "AST-004": ("summer camp outdoor day birds distant", False),
    "AST-005": ("children running playing outdoor morning", False),
    "AST-006": ("fire crackling flames burning wood", False),
    "AST-007": ("children playing shouting outdoor game", False),
    "AST-008": ("quiet room gathering murmur indoor", False),
    "AST-010": ("empty hall quiet reverberation room", False),
    "AST-011": ("country road car pass by rural", False),
    "AST-012": ("kitchen restaurant back room pots pans", False),
    "AST-013": ("lake waterfront gentle waves swimming", False),
    "AST-014": ("cafeteria dining hall crowd chatter", False),
    "AST-015": ("night crickets countryside exterior", False),
    "AST-016": ("dawn birds morning countryside lake", False),
    "AST-017": ("projector film room hum quiet", False),
    "AST-018": ("radio static hiss room tone", False),
    "AST-019": ("empty hall rehearsal room tone", False),
    "AST-020": ("river rapids white water", False),
    "AST-021": ("outdoor field quiet countryside", False),
    "AST-022": ("woods lake swimming nature", False),
    "AST-023": ("audience murmur theatre before show", False),
    "AST-024": ("children humming singing acapella", True),
    "AST-025": ("action running dramatic underscore", False),
    "AST-026": ("wooden flute peaceful melody", False),
    "AST-027": ("chase comedy upbeat instrumental", False),
    "AST-029": ("emotional piano swell romantic", True),
    "AST-030": ("gentle ending piano bittersweet", False),
    "AST-031": ("gentle acoustic ending sentimental", False),
    "AST-032": ("title sting bright short", True),
    "AST-037": ("80s synth rock training montage", False),
    "AST-038": ("acoustic guitar strumming cheerful", False),
    "AST-039": ("romantic kiss sting short", True),
    "AST-040": ("inspirational sports underscore", False),
    "AST-042": ("orchestral hope crescendo short", True),
    "AST-043": ("warm morning acoustic sting", True),
    "AST-045": ("applause crowd cheer", True),
    "AST-046": ("audience boo hiss", True),
    "AST-047": ("audience laughter crowd", True),
    "AST-050": ("motorboat engine water", True),
    "AST-051": ("body fall tumble grass", True),
    "AST-053": ("car door close", True),
    "AST-054": ("clock tick tension", False),
    "AST-055": ("comedy rimshot crickets", True),
    "AST-056": ("plates crash dishes breaking", True),
    "AST-057": ("car crash impact", True),
    "AST-059": ("sci fi device beep power up", True),
    "AST-060": ("dice roll table", True),
    "AST-061": ("door knock creak open", True),
    "AST-062": ("dramatic sting suspense hit", True),
    "AST-063": ("comedy fart", True),
    "AST-064": ("children scream shout", True),
    "AST-066": ("telephone ring classic", True),
    "AST-067": ("phone modem beep trace", True),
    "AST-068": ("metal tray thud impact", True),
    "AST-069": ("rumble earthquake building", True),
    "AST-070": ("running footsteps gravel", True),
    "AST-072": ("slapstick bonk comedy hit", True),
    "AST-073": ("kiss smooch comedy", True),
    "AST-075": ("whoosh transition cinematic", True),
    "AST-076": ("vcr projector hum", False),
    "AST-077": ("bus diesel engine stop start", True),
    "AST-078": ("motorcycle approach pass", True),
    "AST-079": ("pickup truck door engine", True),
    "AST-080": ("van engine accelerate", True),
    "AST-081": ("shout dinner call", True),
    "AST-082": ("water splash dive", True),
    "AST-083": ("whistle sports referee", True),
    "AST-084": ("strong wind gust", True),
    "AST-085": ("gentle breeze wind soft", True),
    "AST-086": ("silence", True),
}

BBC_MEDIA_BASE = "https://sound-effects-media.bbcrewind.co.uk/wav"
BBC_CSV_URL = "https://archive.org/download/BBCSoundEffectsComplete/scripts/BBCSoundEffects.csv"
